### ISSUE TITLE
error[E0432]: unresolved import `crate::implementation::aarch64::neon`

### ISSUE THREAD

**Issue by DaviRain-Su** [simd-lite/simd-json#221]
```
error[E0432]: unresolved import `crate::implementation::aarch64::neon`
   --> /Users/davirain/.cargo/registry/src/github.com-1ecc6299db9ec823/simdutf8-0.1.3/src/basic.rs:223:53
    |
223 |             pub use crate::implementation::aarch64::neon::validate_utf8_basic as validate_utf8;
    |                                                     ^^^^ could not find `neon` in `aarch64`

error[E0432]: unresolved import `crate::implementation::aarch64::neon`
   --> /Users/davirain/.cargo/registry/src/github.com-1ecc6299db9ec823/simdutf8-0.1.3/src/basic.rs:224:53
    |
224 |             pub use crate::implementation::aarch64::neon::ChunkedUtf8ValidatorImp;
    |                                                     ^^^^ could not find `neon` in `aarch64`

error[E0432]: unresolved import `crate::implementation::aarch64::neon`
   --> /Users/davirain/.cargo/registry/src/github.com-1ecc6299db9ec823/simdutf8-0.1.3/src/basic.rs:225:53
    |
225 |             pub use crate::implementation::aarch64::neon::Utf8ValidatorImp;
    |                                                     ^^^^ could not find `neon` in `aarch64`

error[E0432]: unresolved import `crate::implementation::aarch64::neon`
   --> /Users/davirain/.cargo/registry/src/github.com-1ecc6299db9ec823/simdutf8-0.1.3/src/compat.rs:124:53
    |
124 |             pub use crate::implementation::aarch64::neon::validate_utf8_compat as validate_utf8;
    |                                                     ^^^^ could not find `neon` in `aarch64`

For more information about this error, try `rustc --explain E0432`.
error: could not compile `simdutf8` due to 4 previous errors
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by Licenser** [comment]
A bit of context beyond a copy of an error message would really make this a much better ticket. It is really hard to help with something like this.

**Comment by DaviRain-Su** [comment]
thx

**Comment by eugecm** [comment]
Just to add a bit of context: I'm also getting this error while trying to build a project with `simd-json = "0.4.13"` on an M1 mac. `neofetch` reports my system as "OS: macOS 12.1 21C52 arm64".  I've not tried other versions of simd-json though

**Comment by eugecm** [comment]
Interestingly enough, compiling the project on rustc nightly works fine (`rustc 1.61.0-nightly (03918badd 2022-03-07`)

**Comment by Licenser** [comment]
That's quite odd, there code in question it's not in simd-json but in simdutf8, I looked if there is a problem with the way it gets important but I couldn't get it to work on a M1 either. @hkratz do you have an idea by any chance what we're doing wrong with the include `aarch64_neon` is set in the cargo.toml?

**Comment by hkratz** [comment]
I will look into it.

**Comment by hkratz** [comment]
This is now fixed in the simdutf8 main branch. I will cut a release shortly.

But fixing this is not enough to make simd-json work with Rust 1.59. If I edit the simd-json `Cargo.toml` to depend on simdutf8 main I get the next problem in the `value-trait` crate. Should be enough to drop `feature(stdsimd)` as it is no longer required with 1.59.

```
$ cargo build
   Compiling simdutf8 v0.1.3 (/Users/hans/dev/simdutf8)
   Compiling value-trait v0.2.4
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /Users/hans/.cargo/registry/src/github.com-1ecc6299db9ec823/value-trait-0.2.4/src/lib.rs:3:46
  |
3 | #![cfg_attr(target_arch = "aarch64", feature(stdsimd,))]
  |                                              ^^^^^^^
```

**Comment by Licenser** [comment]
got value-trait updated with 0.2.12, simd-value itself is still not happy but otherwise the changes in simdutf8 do the tirck :) I'll update to a new release once it's cut

**Comment by hkratz** [comment]
simdutf8 v0.1.4 has been released.

**Comment by Licenser** [comment]
Yay! Thank you @hkratz !

I made a branch with the collected changes https://github.com/simd-lite/simd-json/pull/222, @eugecm if you could give that a spin and say if it solves your problem it'd be nice. It still requires nightly, it seems not all the needed features have landed in stable yet but it is working on my m1 otherwise :D

**Comment by Licenser** [comment]
Since there was no feedback about this not working I'll close this as resolved.
