### ISSUE TITLE
0.1.17 does not compile

### ISSUE THREAD

**Issue by dtolnay** [simd-lite/simd-json#34]
The 0.1.17 release is failing to build in Travis, when 0.1.16 used to work. Any idea what may be going on here?
https://travis-ci.org/serde-rs/json-benchmark/jobs/565755287

<details>
<summary>error messages</summary>

```console
error[E0425]: cannot find value `SIMDJSON_PADDING` in this scope
   --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/simd-json-0.1.17/src/stage2.rs:256:48
    |
256 |                 let mut copy = vec![0u8; len + SIMDJSON_PADDING];
    |                                                ^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `SIMDJSON_PADDING` in this scope
   --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/simd-json-0.1.17/src/stage2.rs:271:48
    |
271 |                 let mut copy = vec![0u8; len + SIMDJSON_PADDING];
    |                                                ^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `SIMDJSON_PADDING` in this scope
   --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/simd-json-0.1.17/src/stage2.rs:286:48
    |
286 |                 let mut copy = vec![0u8; len + SIMDJSON_PADDING];
    |                                                ^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `SIMDJSON_PADDING` in this scope
   --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/simd-json-0.1.17/src/lib.rs:142:79
    |
142 |         let needs_relocation = (buf_start + input.len()) % page_size::get() < SIMDJSON_PADDING;
    |                                                                               ^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `SIMDJSON_PADDING` in this scope
   --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/simd-json-0.1.17/src/lib.rs:145:62
    |
145 |             let mut data: Vec<u8> = Vec::with_capacity(len + SIMDJSON_PADDING);
    |                                                              ^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `SIMDJSON_PADDING` in this scope
   --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/simd-json-0.1.17/src/lib.rs:167:48
    |
167 |         let strings = Vec::with_capacity(len + SIMDJSON_PADDING);
    |                                                ^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `SIMDJSON_PADDING` in this scope
   --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/simd-json-0.1.17/src/lib.rs:215:40
    |
215 |         let mut copy = vec![0u8; len + SIMDJSON_PADDING];
    |                                        ^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `SIMDJSON_PADDING` in this scope
   --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/simd-json-0.1.17/src/lib.rs:227:18
    |
227 |         if len < SIMDJSON_PADDING {
    |                  ^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `SIMDJSON_PADDING` in this scope
   --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/simd-json-0.1.17/src/lib.rs:228:44
    |
228 |             let mut copy = vec![0u8; len + SIMDJSON_PADDING];
    |                                            ^^^^^^^^^^^^^^^^ not found in this scope

error[E0599]: no function or associated item named `find_structural_bits` found for type `Deserializer<'_>` in the current scope
   --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/simd-json-0.1.17/src/lib.rs:153:31
    |
112 | pub struct Deserializer<'de> {
    | ---------------------------- function or associated item `find_structural_bits` not found for this
...
153 |                 Deserializer::find_structural_bits(&data)
    |                               ^^^^^^^^^^^^^^^^^^^^ function or associated item not found in `Deserializer<'_>`

error[E0599]: no function or associated item named `find_structural_bits` found for type `Deserializer<'_>` in the current scope
   --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/simd-json-0.1.17/src/lib.rs:156:36
    |
112 | pub struct Deserializer<'de> {
    | ---------------------------- function or associated item `find_structural_bits` not found for this
...
156 |             unsafe { Deserializer::find_structural_bits(input) }
    |                                    ^^^^^^^^^^^^^^^^^^^^ function or associated item not found in `Deserializer<'_>`

error[E0599]: no method named `parse_str_` found for type `&'a mut Deserializer<'de>` in the current scope
  --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/simd-json-0.1.17/src/serde/de.rs:21:55
   |
21 |                 visitor.visit_borrowed_str(stry!(self.parse_str_()))
   |                                                       ^^^^^^^^^^

error[E0599]: no method named `parse_str_` found for type `&'a mut Deserializer<'de>` in the current scope
  --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/simd-json-0.1.17/src/serde/de.rs:78:62
   |
78 |                 return visitor.visit_borrowed_str(stry!(self.parse_str_()));
   |                                                              ^^^^^^^^^^

error[E0599]: no method named `parse_str_` found for type `&'a mut Deserializer<'de>` in the current scope
  --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/simd-json-0.1.17/src/serde/de.rs:81:47
   |
81 |         visitor.visit_borrowed_str(stry!(self.parse_str_()))
   |                                               ^^^^^^^^^^

error[E0599]: no method named `parse_str_` found for type `&'a mut Deserializer<'de>` in the current scope
  --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/simd-json-0.1.17/src/serde/de.rs:94:53
   |
94 |                 return visitor.visit_str(stry!(self.parse_str_()));
   |                                                     ^^^^^^^^^^

error[E0599]: no method named `parse_str_` found for type `&'a mut Deserializer<'de>` in the current scope
  --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/simd-json-0.1.17/src/serde/de.rs:97:38
   |
97 |         visitor.visit_str(stry!(self.parse_str_()))
   |                                      ^^^^^^^^^^

error[E0599]: no method named `parse_str_` found for type `Deserializer<'de>` in the current scope
   --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/simd-json-0.1.17/src/value/borrowed.rs:184:29
    |
184 |             b'"' => self.de.parse_str_().map(Value::from),
    |                             ^^^^^^^^^^
    | 
   ::: /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/simd-json-0.1.17/src/lib.rs:112:1
    |
112 | pub struct Deserializer<'de> {
    | ---------------------------- method `parse_str_` not found for this

error[E0599]: no method named `parse_str_` found for type `Deserializer<'de>` in the current scope
   --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/simd-json-0.1.17/src/value/borrowed.rs:199:29
    |
199 |             b'"' => self.de.parse_str_().map(Value::from),
    |                             ^^^^^^^^^^
    | 
   ::: /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/simd-json-0.1.17/src/lib.rs:112:1
    |
112 | pub struct Deserializer<'de> {
    | ---------------------------- method `parse_str_` not found for this

error[E0599]: no method named `parse_str_` found for type `Deserializer<'de>` in the current scope
   --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/simd-json-0.1.17/src/value/borrowed.rs:244:37
    |
244 |             let key = stry!(self.de.parse_str_());
    |                                     ^^^^^^^^^^
    | 
   ::: /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/simd-json-0.1.17/src/lib.rs:112:1
    |
112 | pub struct Deserializer<'de> {
    | ---------------------------- method `parse_str_` not found for this

error[E0599]: no method named `parse_str_` found for type `Deserializer<'de>` in the current scope
   --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/simd-json-0.1.17/src/value/owned.rs:184:29
    |
184 |             b'"' => self.de.parse_str_().map(Value::from),
    |                             ^^^^^^^^^^
    | 
   ::: /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/simd-json-0.1.17/src/lib.rs:112:1
    |
112 | pub struct Deserializer<'de> {
    | ---------------------------- method `parse_str_` not found for this

error[E0599]: no method named `parse_str_` found for type `Deserializer<'de>` in the current scope
   --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/simd-json-0.1.17/src/value/owned.rs:199:29
    |
199 |             b'"' => self.de.parse_str_().map(Value::from),
    |                             ^^^^^^^^^^
    | 
   ::: /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/simd-json-0.1.17/src/lib.rs:112:1
    |
112 | pub struct Deserializer<'de> {
    | ---------------------------- method `parse_str_` not found for this

error[E0599]: no method named `parse_str_` found for type `Deserializer<'de>` in the current scope
   --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/simd-json-0.1.17/src/value/owned.rs:244:37
    |
244 |             let key = stry!(self.de.parse_str_());
    |                                     ^^^^^^^^^^
    | 
   ::: /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/simd-json-0.1.17/src/lib.rs:112:1
    |
112 | pub struct Deserializer<'de> {
    | ---------------------------- method `parse_str_` not found for this
```
</details>

**Comment by dtolnay** [comment]
Looks like it's fixed by setting target-cpu=native in Travis. We only run `cargo check` there so it hadn't been needed so far. Would it make sense to have a fallback path when neither sse4.2 nor avx2 are available so that we support `cargo check` of crates that depend on this crate?

**Comment by Licenser** [comment]
I suspect I do, 0.1.17 introduced SSE4.2 support and removed fallback to filler instructions for SIMD code. 

Rusts default is to not use native CPU targets (or avx/sse) it seems and from looking at the .travis.yaml RUSTFLAGS is not set.

Forcing a compatible SIMD instruction-set to be enabled seems somewhat sensibel, the original change forced that, but I'm open to a discussion. It seems that 'you have to set RUSTC  flags' isn't as clear as I thought it would be.

I wonder what the best approach is.

Not forcing it leaves people with a possible bad experience since without SIMD simdjson is just json and brings no benefits over 'easier' parsers.

Forcing it means people get in situations where it's not clear why the compilation failed.

Perhaps adding a feature flag to allow 'fallback' mode would be a good alternative?

**Comment by dtolnay** [comment]
Makes sense, feel free to close if this is not supported. I don't think a feature flag for 'fallback' mode would have helped in this case so I would rather not have that -- it's about as easy to set target-cpu in .cargo/config as it is to set a Cargo flag.

A reasonably friendly option would be to introduce a deliberate link error if simd isn't available. This way cargo check will work (doesn't need to link) but cargo build won't let you make a non-simd binary. See https://github.com/dtolnay/no-panic for an example. You could do something like:

```console
undefined reference to `

    ERROR[simd-json]: simd support is required; set environment variable RUSTFLAGS='-C target-cpu=native'
    '
```

**Comment by Licenser** [comment]
I like that idea!

**Comment by Licenser** [comment]
@sunnygleason since you did the sse4.2 work I'm curious on what your take is? Should building unoptimised versions be allowed?

**Comment by Licenser** [comment]
Those are the intrinsics I found in @lemire's arm64 implementation

* [x] vaddq_s8
* [ ] vandq_u8
* [ ] vceqq_s8
* [ ] vceqq_u8
* [ ] vcgtq_s8
* [ ] vcleq_u8
* [ ] vdupq_n_s8
* [ ] vdupq_n_u8
* [ ] vextq_s8
* [ ] vget_lane_u64
* [ ] vgetq_lane_u16
* [ ] vgetq_lane_u64
* [ ] vld1q_s8
* [ ] vld1q_u8
* [ ] vmovq_n_u8
* [ ] vmull_p64
* [ ] vorrq_s8
* [ ] vorrq_u8
* [ ] vpaddq_u8
* [ ] vqmovn_u64
* [ ] vqsubq_u8
* [x] vqtbl1q_s8
* [x] vqtbl1q_u8
* [ ] vreinterpret_u64_u32
* [ ] vreinterpretq_s8_u8
* [ ] vreinterpretq_u16_u8
* [ ] vreinterpretq_u64_u8
* [ ] vreinterpretq_u8_s8
* [ ] vshrq_n_u8
* [ ] vld1q_u8
* [ ] vst1q_u8
* [ ] vmovq_n_u8
* [ ] vceqq_u8
* [ ] vandq_u8
* [ ] vpaddq_u8
* [ ] vgetq_lane_u32
* [ ] vreinterpretq_u32_u8

**Comment by sunnygleason** [comment]
@Licenser I was actually thinking of writing a 'basic' 64-bit implementation, if nothing else than for comparison purposes and general platform ubiquity. Do you like that idea?

**Comment by Licenser** [comment]
Allowing a fallback is as simple as removing the sse4 guard. Rust is smart enough to replace the simd intrinsic with plain x86 code. The drawback is that the he default compiler settings will default to that and give users surprisingly bad experience
